//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSCOM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReg
    {
        public int ID { get; set; }
        public string Business_Name { get; set; }
        public string Business_Link { get; set; }
        public string Contact_No { get; set; }
        public string GST_No { get; set; }
        public string Upload_GST_Certificate { get; set; }
        public string IDA_Registration { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Street { get; set; }
        public string Landmark { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Pincode { get; set; }
    }
}
